var requiredFields = ["t", "wid", "len", "wei"];
var config_data = {
  title: "Scouting PASS 2025",
  dataFormat: "tsv",
  page_title: "Reefscape Pit Scouting",
  pitConfig: "true",
  prematch: [
    {
      name: "Event",
      code: "e",
      type: "event",
      defaultValue: "2025dal",
      required: "true",
      disabled: "true",
    },
    { name: "Team Number", code: "t", type: "team" },
    { name: "Width (with bumpers)", code: "wid", type: "number" },
    { name: "Length (with bumpers)", code: "len", type: "number" },
    { name: "Weight (with bumpers)", code: "wei", type: "number" },
    {
      name: "No Bumpers1",
      title: "If no bumpers, add 8 inches to width and length",
      code: "nb",
      type: "divider",
    },
    {
      name: "No Bumpers2",
      title: "If no bumpers, add 15 pounds to weight",
      code: "nb2",
      type: "divider",
    },
    {
      name: "Drivetrain",
      code: "drv",
      type: "radio",
      choices: {
        Swerve: "Swerve<br>",
        Tank: "West Coast/Tank<br>",
        Mechanum: "Mechanum<br>",
        Other: "Other",
      },
      defaultValue: "s",
    },
    {
      name: "Other Drivetrain",
      code: "odt",
      type: "text",
      size: 20,
      maxSize: 50,
    },
    {
      name: "Swerve Ratio",
      code: "sr",
      type: "radio",
      choices: {
        1: "L1 (8.14:1)<br>",
        2: "L2 (6.75:1)<br>",
        3: "L3 (6.12:1)<br>",
        4: "L4 (5.14:1)<br>",
        o: "Other ratio (put in comments)<br>",
        x: "Not Swerve",
      },
      defaultValue: "3",
    },
    {
      name: "Drivetrain Motor",
      code: "mot",
      type: "radio",
      choices: {
        Neo: "Neo<br>",
        Falcon: "Falcon<br>",
        CIM: "CIM<br>",
        Kraken: "Kraken<br>",
        Other: "Other<br>",
      },
      defaultValue: "f",
    },
    { name: "# of Batteries", code: "nob", type: "number" },
    { name: "Floor pickup Coral", code: "fpc", type: "bool" },
    { name: "Floor pickup Algae", code: "fpa", type: "bool" },
    {
      name: "How to Feed Robot?",
      code: "feed",
      type: "radio",
      choices: {
        Vertical: "Vertical<br>",
        Horizontal: "Horizontal<br>",
        Either: "Either<br>",
        Other: "Other",
      },
      defaultValue: "Vertical",
    },
    { name: "Autos", code: "aut", type: "text", size: 20, maxSize: 500 },
    {
      name: "Scouting Method /<br>Program (ScoutingPASS?)",
      code: "sct",
      type: "text",
      size: 20,
      maxSize: 250,
    },
    { name: "Comments", code: "co", type: "text", size: 20, maxSize: 250 },
    { name: "Is the robot fish-like?", code: "fish", type: "bool" },
    {
      name: "Explain fish-like",
      code: "fishex",
      type: "text",
      size: 20,
      maxSize: 250,
    },
    {
      name: "Will this robot survive a water game?",
      code: "water",
      type: "bool",
    },
    {
      name: "Explain water game",
      code: "waterex",
      type: "text",
      size: 20,
      maxSize: 250,
    },
  ],
};
